// auth
export const CREATE_TOKEN = 'CREATE_TOKEN'
export const DELETE_TOKEN = 'DELETE_TOKEN'
// aritcle
export const CREATE_ARTICLE = 'CREATE_ARTICLE'
export const GET_ALL_ARTICLE = 'GET_ALL_ARTICLE'
export const GET_CURRENT_ARTICLE = 'GET_CURRENT_ARTICLE'
export const SAVE_ARTICLE = 'SAVE_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE'
export const NOT_PUBLISH_ARTICLE = 'NOT_PUBLISH_ARTICLE'
